apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: phpadmin-pod
  name: phpadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: phpadmin-pod
  template:
    metadata:
      labels:
        run: phpadmin-pod
    spec:
      containers:
        - image: phpmyadmin
          name: phpadmin-pod
          envFrom:
            - configMapRef:
                name: phpadmin-config
            - secretRef:
                name: phpadmin-secret
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
