apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpadmin
  template:
    metadata:
      labels:
        app: phpadmin
    spec:
      containers:
        - name: phpadmin-pod
          image: phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: 10.109.180.44  # Dirección IP de tu servidor MySQL
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword

