apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql-pod
  template:
    metadata:
      labels:
        run: mysql-pod
    spec:
      containers:
        - image: mysql
          name: mysql-pod
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          resources: {}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
